### ISSUE TITLE
Misleading `INCLUDE_DEPLOYMENTS: true` for CATS

### ISSUE THREAD

**Issue by hsiliev** [cloudfoundry-incubator/eirini-release#123]
### Description

Deployments CATS are enabled, but since they depend on V3 tests they are skipped in CI

### Steps to reproduce

Execute CATS in CI

### What was expected to happen

Do not include deployments (https://github.com/cloudfoundry-incubator/eirini-ci/blob/7fd82ea15666ac2e92767cba12d76faf3ac47691/pipelines/modules/run-core-cats.yml#L35) until V3 are enabled

### What actually happened

Misleading `INCLUDE_DEPLOYMENTS: true` param

### Suggested fix (optional)

Remove ` INCLUDE_DEPLOYMENTS: true` from CI

### Additional information (optional)

na

**Comment by alex-slynko** [comment]
Fixed in https://github.com/cloudfoundry-incubator/eirini-release/commit/759c0fdfdd34235475e827c99ed2ea9f85b5563a
