### ISSUE TITLE
TCP Routing tests not executed as part of CATS

### ISSUE THREAD

**Issue by hsiliev** [cloudfoundry-incubator/eirini-release#124]
### Description

While comparing Diego & Eirini features I decided to take a look at the CATS that are used to confirm feature parity. Turns out TCP Routing tests are not included.

### Steps to reproduce

Execute CATS

### What was expected to happen

TCP Routing should be clearly marked as supported (or unsupported?)

### What actually happened

It's not clear if Eirini installation can pass the TCP Routing tests or not.

### Suggested fix (optional)

Explicitly specify either `INCLUDE_TCP_ROUTING: true` or `INCLUDE_TCP_ROUTING: false` in config

### Additional information (optional)

na

**Comment by julz** [comment]
Hi @hsiliev - we have a story coming up very soon in the backlog (https://www.pivotaltracker.com/story/show/168838261) to document which CATs are/aren't expected to pass in 1.0 (which we hope to ship quite soon 🤞). You can follow this story in tracker to be notified when we complete it.
