### ISSUE TITLE
/tmp/lifecycle/shell missing from app pods

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/eirini-release#126]
After deploying SCF/Eirini, I `kubectl exec -ti -n scf-eirini` into a pod, and tried to access `node -v` after setting up the environment as per [1]:

```
$ /tmp/lifecycle/shell
bash: /tmp/lifecycle/shell: No such file or directory
```

[1] https://docs.cloudfoundry.org/devguide/deploy-apps/ssh-apps.html#-ssh-session-environment

**Comment by akshaymankar** [comment]
Hi @drnic 

We don't support `cf ssh` yet. You can try the [eirini-ssh](https://github.com/SUSE/eirini-ssh/) project, the folks who developed it tell me that it has full compatibility with diego.
