### ISSUE TITLE
Cannot deploy CF on Kubernetes

### ISSUE THREAD

**Issue by joaquinito01** [cloudfoundry-incubator/eirini-release#145]
### Description

I are installing CF on Kubernetes, but appears error.

### Steps to reproduce

  Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "PodSecurityPolicy" in version "extensions/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta1"]

### What was expected to happen

Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "PodSecurityPolicy" in version "extensions/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta1"]

### What actually happened

Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "PodSecurityPolicy" in version "extensions/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta1"]

**Comment by julz** [comment]
Hi @joaquinito01 - could you let us know what version of Eirini and Kubernetes you are using, and which install method (i.e. is it the one in this repo's README or something else), please?

**Comment by joaquinito01** [comment]
Kubernetes: 1.16.5
Eirini: 1.0.0

**Comment by joaquinito01** [comment]
helm install eirini/uaa --namespace uaa --name uaa --values values.yaml

**Comment by giner** [comment]
Related to some APIs being promoted in k8s 1.16 https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

**Comment by joaquinito01** [comment]
Yes.

**Comment by alex-slynko** [comment]
Hi @joaquinito01 
This should work in the latest version of Eirini.
