### ISSUE TITLE
Eirini docker app support only supports port 8080

### ISSUE THREAD

**Issue by jandubois** [cloudfoundry-incubator/eirini-release#147]
Deploying a docker app with Eirini only works if it uses port 8080.

The documentation claims that CF will parse the `Exposed Port` from the container metadata. See "Port Configuration" on https://docs.cloudfoundry.org/devguide/deploy-apps/push-docker.html:

>When configuring a Docker image for CFAR, you can control the exposed port and the corresponding value of PORT by specifying the EXPOSE directive in the image Dockerfile. If you specify the EXPOSE directive, then the corresponding app pushed to CFAR listens on that exposed port. For example, if you set EXPOSE to 7070, then the app listens for connections on port 7070.

I've verified this with the `nginxdemos/hello` image, which uses port 80:

```
$ docker inspect --format "{{.Config.ExposedPorts}}" nginxdemos/hello
map[80/tcp:{}]
```

This app works fine when deployed with Diego, but fails to start with Eirini. Inspecting the pod shows that Eirini has not detected the correct port settings:

```
Containers:
  opi:
    Port:           8080/TCP
    [...]
    Environment:
      VCAP_APP_HOST:            0.0.0.0
      VCAP_APP_PORT:            8080
      PORT:                     8080
      CF_INSTANCE_PORTS:        [{"external":8080,"internal":8080}]
      CF_INSTANCE_ADDR:         0.0.0.0:8080
      CF_INSTANCE_PORT:         8080
```

**Comment by gdankov** [comment]
Hello @jandubois,

We are aware of this and we have [a story](https://www.pivotaltracker.com/story/show/169060978) for it in icebox.

**Comment by viovanov** [comment]
@gdankov can this be closed now? looks like the tracker story is closed

**Comment by troytop** [comment]
https://www.pivotaltracker.com/n/projects/2172361/stories/169060978

**Comment by gdankov** [comment]
@viovanov Yup, this can be closed now, thanks.
