### ISSUE TITLE
Deploying an app with multiple buildpacks is not supported by eirini-staging

### ISSUE THREAD

**Issue by stoyanr** [cloudfoundry-incubator/eirini-release#149]
### Description

Deploying an app with multiple buildpacks as described in [How Buildpacks Work in CFAR](https://docs.cloudfoundry.org/buildpacks/understand-buildpacks.html) is not really supported by [eirini-staging](https://github.com/cloudfoundry-incubator/eirini-staging).

### Steps to reproduce

Deploy an app with multiple buildpacks specified in its manifest. In my case, I have an app with one standard buildpack (`java_buildpack`) and one custom buldpack:

```
- buildpacks:
  - uas_dataflow_server_buildpack
  - java_buildpack
```

### What was expected to happen

The sequence of interactions as specified in [No Buildpack Detection](https://docs.cloudfoundry.org/buildpacks/understand-buildpacks.html#no-detection). In this case , the `supply` script of the first buildpack should be invoked, and then the application should start with the second buildpack.

### What actually happened

Depending on whether or not the first buildpack has a detect script that returns 0, one of the following outcomes:
* If the first buildpack has a `detect`` script that returns 0, this buildpack is "detected" and the second buildpack is ignored. The app fails to start.
* If the first buildpack doesn't have a `detect` script or it returns 1, this buildpack is simply ignored. The app starts with the second buildpack, but since the `supply` script of the first buildpack was never called, the app doesn't work as expected.

### Suggested fix (optional)

The bug is in https://github.com/cloudfoundry-incubator/eirini-staging/blob/ae1327186284f350673df0d5e3b4f21045fd71fa/builder/config.go#L48-L55 . The `skipDetect` flag is never set if `len(buildpacks) > 0`. To fix this issue, this flag should be set if `len(buildpacks) > 0` and the `skipDetect` flags of all buildpacks are `true`.

### Additional information (optional)

Discussed with @georgethebeatle . I intend to open a PR for the fix.

**Comment by julz** [comment]
thanks @stoyanr, we'll be very happy to accept a PR to fix this - do let us know if we can help with anything!
