### ISSUE TITLE
CF CLI command restart-app-instance didn't start the instance with Eirini 

### ISSUE THREAD

**Issue by EmilyEmily** [cloudfoundry-incubator/eirini-release#153]
### Description

  [After setup eirini 1.0 release on IKS cluster,  cf restart-app-instance [...] CLI call returned 204, but it only deleted the instance pod, and didn't start the instance.]

### Steps to reproduce
```
# cf push my-app
# cf restart-app-instance my-app 0
Restarting instance 0 of application my-app as admin
OK
# cf apps
Getting apps in org system / space dev as admin...
OK
name                               requested state   instances   memory   disk   urls
my-app   started           0/1         128M     128M   my-app.teststream.eu-de.containers.appdomain.cloud]
```

### What was expected to happen

  The respective instance of the app is restarted.

### What actually happened

  As shown in "Steps to reproduce", application instance was not running after the command.

**Comment by julz** [comment]
We haven't been able to reproduce this. Please do re-open if you weren't able to resolve this.
