### ISSUE TITLE
NetworkPolicy prevents calling apps

### ISSUE THREAD

**Issue by jkbschmid** [cloudfoundry-incubator/eirini-release#155]
### Description
I tried to deploy cf-for-k8s and run its smoke test. I manage to cf push the docker image, but the subsequent HTTP-GET always failed.

I found out that a misconfigured NetworkPolicy from eirini called `deny-app-ingress` is responsible for prohibiting all traffic to apps that does not come from the `cf-system` namespace.
Since the GET in the smoke test is routed via the `istio-ingress` in the `istio-system` namespace, the connection is dropped.

### Steps to reproduce

Deploy cf-for-k8s using the scripts from github.com/cloudfoundry/cf-for-k8s.

### What was expected to happen

I can successfully execute the smoke-tests which pushes a docker image and curls the app.
There is no networkpolicy prohibitting traffic via the istio-ingress.

### What actually happened

  The HTTP-GET in the smoke-test fails with error code 503, since the network policy `deny-app-ingress` prohibits traffic from the istio-system namespace which is where the istio-ingress is deployed.

### Suggested fix (optional)

 Add istio-system namespace to list of allowed namespaces.

**Comment by julz** [comment]
I think this is going to be fixed inside of `cf-for-k8s` (and `KubeCF`/`cf-networking-for-k8s`) so closing the issue here. Thanks!
