### ISSUE TITLE
Can we implement Eirini on Kubernetes 1.15 

### ISSUE THREAD

**Issue by KshitijaRadke** [cloudfoundry-incubator/eirini-release#157]
We are having Kubernetes cluster 1.15 deployed and planning to implement Eirini on that.
Can we go head for that.

**Comment by alex-slynko** [comment]
Hi @KshitijaRadke 

Eirini should work with Kubernetes 1.15. Do you have any problems with it?

**Comment by KshitijaRadke** [comment]
Hi @alex-slynko 

To verify the cluster requirements, tried to run kube-ready-state-check.sh on worker node and script failed with Configuration problem detected: Privileged must be enabled in 'kubelet'.

Any suggestion for this.

**Comment by alex-slynko** [comment]
Hi @KshitijaRadke 

This script is coming from [SCF](https://github.com/SUSE/scf). Eirini itself does not require privileged containers.
Right now we are working on integrating with [KubeCF](https://github.com/cloudfoundry-incubator/kubecf). You can clarify it in these repositories.	
We plan to remove SCF parts from our repository and focus only on deploying Eirini itself.

As for privileged, most of Kubernetes installations I know of, allow operators to enable privileged containers. Please check the documentation for your installer. For example, in PKS you have to enable `Allow Privileged` in the plan to make it work.

**Comment by KshitijaRadke** [comment]
@alex-slynko  Thanks for the inputs.
