### ISSUE TITLE
UAA pod is not in ready state

### ISSUE THREAD

**Issue by KshitijaRadke** [cloudfoundry-incubator/eirini-release#159]
### Description
Referring https://github.com/cloudfoundry-incubator/eirini-release/blob/master/docs/installation.md for deployment after performing step 5 UAA pod is not in ready state giving, 
waiting 30s trying: detect mysql-proxy-set.KUBERNETES_NAMESPACE.svc.KUBERNETES_CLUSTER_DOMAIN 3306 failed
Giving up
uaa-pre-start - starting 
trying to run update-ca-certificates
Starting monit daemon with http interface at

Readiness probe failed: Waiting for monit to be ready when checked with describe

Any inputs for this

**Comment by alex-slynko** [comment]
Hi @KshitijaRadke 

We plan to remove SCF bits from eirini-release. The recommended ways to install Eirini are [KubeCF](https://github.com/cloudfoundry-incubator/kubecf) and [CF-for-K8s](https://github.com/cloudfoundry/cf-for-k8s). Please use those installers.
