### ISSUE TITLE
Failed to pull image/filesystem layer verification failed for digest 

### ISSUE THREAD

**Issue by bkrannich** [cloudfoundry-incubator/eirini-release#18]
With my current deployment of https://github.com/cloudfoundry-incubator/eirini-release/tree/master/scf on Gardener (setup as described in https://github.com/cloudfoundry-incubator/eirini-release/pull/13), I am able to `cf push` my app once. Pushing it subsequently leads to:

```
Failed to pull image "<value_of:kube/external_ips>:5800/cloudfoundry/app-name:<guid>": rpc error: code = Unknown desc = filesystem layer verification failed for digest sha256:<other_guid>
```

Here is what I have:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:20:58Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.8", GitCommit:"7eab6a49736cc7b01869a15f9f05dc5b49efb9fc", GitTreeState:"clean", BuildDate:"2018-09-14T15:54:20Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

$ kubectl describe node
System Info:
<...>
 Container Runtime Version:  docker://18.6.1
 Kubelet Version:            v1.10.8
 Kube-Proxy Version:         v1.10.8

# on the Kubernetes node
$ docker --version
Docker version 18.06.1-ce, build e68fc7a

$ docker images
# doesn't show any images from <value_of:kube/external_ips>/cloudfoundry/app-name
```

**Comment by bkrannich** [comment]
Ok, tried this again with a Gardener Kubernetes 1.11.3 cluster and the error doesn't occur there. Here, I have:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:20:58Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

$ kubectl describe node
<...>
 Container Runtime Version:  docker://18.6.1
 Kubelet Version:            v1.11.3
 Kube-Proxy Version:         v1.11.3

$ docker --version
Docker version 18.06.1-ce, build e68fc7a
```

So, no difference in the Docker version. And, unless there were changes in the underlying Docker images used by Eirini which are not versioned, I'd assume it's the exact same Eirini bits.

**Comment by mnitchev** [comment]
Hi Bernd,

We fixed the issue in this [commit](https://github.com/cloudfoundry-incubator/eirini/commit/9c2157d2935374f85b23b09037083114136351e3) and it should be already in the latest eirini image. It turned out that we were not properly storing the droplet in our internal blobstore and it was lost after the first pull. It worked for us because our cluster was caching the images, so it was only pulling one time. You should try it in your environment to confirm that everything is working now.

BR,
Mario & @gdankov

**Comment by bkrannich** [comment]
Ok, tested with 9cb8a3a and at least in the tests I did so far, the above issue did no longer occur, so I would close this issue for now.
