### ISSUE TITLE
Check out Ginkgo 2.0

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry-incubator/eirini-release#189]
[Ginkgo 2.0](https://github.com/onsi/ginkgo/tree/v2) is about to come out and it would be nice to try it on our test suite!

The team have published [a document](https://docs.google.com/document/d/1h28ZknXRsTLPNNiOjdHIO-F2toCzq4xoZDXbfYaBdoQ/edit) with the new features that are shipping with 2.0 and the ones that are being removed.

**Comment by kieron-dev** [comment]
Finishing this.

We've pushed some changes to master that work with ginkgo v1 which will smooth the way for accepting v2 when it comes out. However, there will still be manual work to do to change the flags passed to ginkgo in our scripts. All flags are now 'kebab-cased', and some names have changed slightly. E.g. `-randomizeAllSpecs` must change to `--randomize-all`.
