### ISSUE TITLE
Delete a `Task` `Job` after its grace period

### ISSUE THREAD

**Issue by danail-branekov** [cloudfoundry-incubator/eirini-release#195]
Acceptance
* Make sure that the task reporter is not running (because it is not needed for a CR setup - it talks to the CC which is not available in an Eirini-only setup and has a side effect of deleting jobs)
* Create a task via a custom resource
* Wait for the task to complete (either complete successfully, or fail)
* Make sure the K8S job stays around for at least the grace period
* Wait for the job deletion grace period
* See that the job is eventually gone
* Make sure that the K8S job is not recreated (by e.g. the tasks controller)

**Comment by kieron-dev** [comment]
As part of https://github.com/cloudfoundry-incubator/eirini-release/issues/198, we have introduced a check in the task-reporter which stops the reconciliation when it discovers a job is owned by a Task CR. Soon to be pushed. That helps this story a little bit, as it won't matter if the task-reporter is running or not.
