### ISSUE TITLE
Get instances of an LRP custom resource

### ISSUE THREAD

**Issue by danail-branekov** [cloudfoundry-incubator/eirini-release#201]
The REST API can [get the instances of an LRP](https://github.com/cloudfoundry-incubator/eirini/blob/bb3251269759b218d2ab03256ab6a5f3d164ec30/handler/handler.go#L62) which is currently not possible with the LRP custom resource.

We want to do this by introducing an `Instance` CRD, and create an `Instance` resource per instance in the `LRP`. The CRD should have the same fields as the JSON representation in the REST API, as long as it makes sense.

**Comment by gcapizzi** [comment]
We [already apply annotations](https://github.com/cloudfoundry-incubator/eirini/blob/master/k8s/stset/lrp_to_statefulset.go#L164-L177) with labels that make it easy to retrieve the list of `Pod`s belonging to an `LRP`, similarly to what happens for `StatefulSet`s or `Deployment`s, which is enough for now. We might revisit this in the future.
