### ISSUE TITLE
Stop a specific instance of an LRP custom resource

### ISSUE THREAD

**Issue by danail-branekov** [cloudfoundry-incubator/eirini-release#202]
The REST API provides the capability to [stop a specific LRP instance](https://github.com/cloudfoundry-incubator/eirini/blob/bb3251269759b218d2ab03256ab6a5f3d164ec30/handler/handler.go#L61) which is currently not possible with the LRP custom resource.

See #201 for details on how we want to implement the `Instance` CRD. Stopping an instance should be achieved by deleting the corresponding resource. Our controller should delete the corresponding `Pod` and recreate the `Instance` once the new `Pod` is recreated by the `StatefulSet`.

**Comment by gcapizzi** [comment]
We [already apply annotations](https://github.com/cloudfoundry-incubator/eirini/blob/master/k8s/stset/lrp_to_statefulset.go#L164-L177) with labels that make it easy to retrieve the list of `Pod`s belonging to an `LRP`, similarly to what happens for `StatefulSet`s or `Deployment`s, which is enough for now. We might revisit this in the future.
