### ISSUE TITLE
Remove the `UserDefinedAnnotations` property from the LRP custom resource

### ISSUE THREAD

**Issue by danail-branekov** [cloudfoundry-incubator/eirini-release#204]
Custom resource users could put their custom annotations in the LRP CR metadata itself, rather than have a dedicated CR property about it.

**Comment by gcapizzi** [comment]
`UserDefinedAnnotations` is used to annotate the `StatefulSet` and `Pod`s we deploy, so it is actually useful and we're going to keep it for now!
