### ISSUE TITLE
Disambiguate names for various ConfigMaps

### ISSUE THREAD

**Issue by jspawar** [cloudfoundry-incubator/eirini-release#206]
### Description

We noticed that in a cf-for-k8s installation that Eirini's ConfigMaps are named a bit ambiguously. For example, the ConfigMap for the LRP CRD controller is simply called `controller`.

### Steps to reproduce

1. Deploy cf-for-k8s
2. `kubectl get configmaps -n cf-system`

### Suggested fix (optional)

Prefix the names of the ConfigMaps with `eirini-` or something similar to make it clear these are Eirini's ConfigMaps and not some other `api` or `controller` service.

Thank you!

**Comment by gcapizzi** [comment]
Thanks @jspawar! We had a chat about this with the team and there is probably more resources than need renaming beyond `ConfigMap`s - it's top of backlog!
