### ISSUE TITLE
Explore `ytt` for our Concourse pipelines

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry-incubator/eirini-release#209]
At the moment our [Concourse pipelines](https://github.com/cloudfoundry-incubator/eirini-ci) are built on top of [Aviator](https://github.com/herrjulz/aviator) which in turn is based on [Spruce](https://github.com/geofffranks/spruce).

The current solution features a lot of indirection, with `aviator.yml` files glueing lots of small files together and no place showing the structure of the pipeline. We load config values by merging a `config` section to the YAML (which is ignored by Concourse) and then [`grab` them](https://github.com/cloudfoundry-incubator/eirini-ci/blob/master/modules/jobs/bump-go-modules-eirini.yml#L21).

I propose we try to use [`ytt`](https://carvel.dev/ytt) to simplify our pipelines without losing the possibility to reuse jobs and resources. Interesting features to look at:
- [`data.read()`](https://carvel.dev/ytt/#example:example-load-data-files) to inject the content of a text file (could be used instead of `file` e.g. [here](https://github.com/cloudfoundry-incubator/eirini-ci/blob/master/modules/jobs/bump-go-modules-eirini.yml#L33)).
- [`@data/values`](https://carvel.dev/ytt/#example:example-load-data-values) to load config values (instead of having a `config` block and `grab` like [here](https://github.com/cloudfoundry-incubator/eirini-ci/blob/master/modules/jobs/bump-go-modules-eirini.yml#L21)).
- [Functions](https://carvel.dev/ytt/#example:example-function) to abstract YAML fragments with parameters. I suspect this could replace many `config` values.

**Comment by kieron-dev** [comment]
All pipelines migrated to use YTT templating. Old aviator config removed.
