### ISSUE TITLE
Contributing guidelines test script is missing

### ISSUE THREAD

**Issue by mattysweeps** [cloudfoundry-incubator/eirini-release#35]
`./scripts/check-everything.sh` is referenced in https://github.com/cloudfoundry-incubator/eirini-release/blob/develop/.github/contributing.md#unit-tests--static-checks but it does not exist.

It should either exist or the documentation should be updated to remove references to it.

**Comment by mnitchev** [comment]
Fixed by https://github.com/cloudfoundry-incubator/eirini-release/commit/fba30ff83e7f6a4fa46211120ccf9936da36f538
