### ISSUE TITLE
eirinifs.tar file not found in blobstore causing bits container ending in CrashLoopBackOff.

### ISSUE THREAD

**Issue by mikkrish** [cloudfoundry-incubator/eirini-release#53]
### Description

bits container not starting

log:
```
{"level":"info","ts":1552911988.4398773,"caller":"bitsgo/factory.go:334","msg":"Creating local blobstore","path-prefix":"/"}
{"level":"debug","ts":1552911988.4399006,"caller":"local/local_blobstore.go:38","msg":"GetNoRedirect","local-path":"/assets/eirinifs.tar"}

panic: Could not find assets/eirinifs.tar in root FS blobstore. Please make sure that copy it to the root FS blobstore as part of your deployment.

goroutine 1 [running]:
github.com/cloudfoundry-incubator/bits-service/oci_registry.NewBitsImageManager(0xec2bc0, 0xc420439ca0, 0xec2aa0, 0xc420438b70, 0xec2aa0, 0xc420438b70, 0x0)
	/tmp/build/37652675/bits-service-release/src/github.com/cloudfoundry-incubator/bits-service/oci_registry/registry.go:103 +0x249
main.main()
	/tmp/build/37652675/bits-service-release/src/github.com/cloudfoundry-incubator/bits-service/cmd/bitsgo/main.go:63 +0x1a5f
```

### Steps to reproduce

Normal installation via helm

### What was expected to happen

bits container should start

### What actually happened

assets/eirinifs.tar file was not created / copied into blobstore

### Suggested fix (optional)

Probably caused by commit:
[82fd766dfb1811069d613017db7ea79c332d4a18](https://github.com/cloudfoundry-incubator/eirini/commit/82fd766dfb1811069d613017db7ea79c332d4a18)

//Edit:
Probably fixed by:
[017c734818fe60e10ca89f0df74bd48799f4898b](https://github.com/cloudfoundry-incubator/eirini-release/pull/51/commits/017c734818fe60e10ca89f0df74bd48799f4898b)

### Additional information (optional)

Bulild and copy initialized by:
https://github.com/cloudfoundry-incubator/eirini-release/blob/master/scripts/buildfs.sh

**Comment by gdankov** [comment]
Hi @mikkrish,

We think the problem was already fixed. Can you verify and close the issue if that's the case?

Thanks,
@gdankov & @JulzDiverse
