### ISSUE TITLE
Deploy eirini and/or apps to specific nodepools

### ISSUE THREAD

**Issue by mattysweeps** [cloudfoundry-incubator/eirini-release#64]
### Description

It is often useful to deploy CF and its apps to specific nodepools.

### Suggested fix (optional)

This can be configured by adding a nodeSelector block to the helm charts.

This is a common pattern used in helm/charts
https://github.com/helm/charts/search?q=nodeSelector&unscoped_q=nodeSelector

This might best be solved by updating SCF alongside the eirini helm chart, instead of tacking functionality on top of the generated helm charts

**Comment by julz** [comment]
Hi @mattysweeps :)) - I think I agree this one is best for the SCF folks to handle /cc @viovanov
