### ISSUE TITLE
Supporting Ingress rather than LoadBalancer services

### ISSUE THREAD

**Issue by aegershman** [cloudfoundry-incubator/eirini-release#70]
### Description

In order to leverage existing Ingress Controllers for a cluster and reduce waste of outward-facing IPs/loadbalanacers && overall reduce deployment complexity (I... I think?), it would be beneficial to have the option to use an Ingress rather than Service: LoadBalancer for services.

### Additional information (optional)

E.g. something [similar to the `suse/scf` chart part](https://github.com/SUSE/scf/blob/develop/chart-parts/ingress.yaml) for Ingress...?

Thanks so much for your time & consideration.

**Comment by julz** [comment]
Hi @aegershman - sorry about the slow response to this, the corresponding story got lost in the Tracker icebox :(. Can you talk to me a bit more about what we mean by "services" above? Is this referring to CF apps or something else?

**Comment by aegershman** [comment]
No worries at all-- I meant in the context of the cluster components, e.g. being able to configure `ingress` for a service (like cloud controller) rather than requiring the `svc` for the cloud controller use a LoadBalancer. I was referring to the deployment of eirini itself.

Perhaps this is either new, or I just missed it at the time, but it looks like there's more support for leveraging an Ingress controller? https://github.com/cloudfoundry-incubator/eirini-release/blob/master/helm/cf/templates/ingress.yaml

I think we can close this out though?

**Comment by julz** [comment]
Gotcha, yeah, this may be an ask for the fissile folks in that case - thanks for the issue @aegershman!
