### ISSUE TITLE
Eirini regression on app environment variable handling

### ISSUE THREAD

**Issue by michaelgrifalconi** [cloudfoundry-incubator/eirini-release#76]
### Description

Applications deployed with eirini with a special environment variable with a ":" in the name will never end up in a pod.

Example:
```
env:
  "TE:ST": "bla" 
```

CF will wait until the health check timeout but no pod gets created and we were not able to find a detailed error other than the timeout.

### Steps to reproduce

  [You can use this application as example](https://github.com/michaelgrifalconi/eirini-regression-demoapp)
```cf push eirini-regression-app```

### What was expected to happen

The app should be deployed without errors like it happens on CF using diego and the variable should be present

```
 cf env eirini-regression-app
Getting env variables for app eirini-regression-app in org MYORG / space MYSPACE as MYUSER...
OK

System-Provided:
[...]

User-Provided:
TE:ST: bla
```

### What actually happened

```
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
FAILED
Error restarting application: Start app timeout
```

### Additional information

One use case of this unusual variable name would be the following:

```
"npm_config_@sap:registry":"https://npm.sap.com"
```

This is to setup npm_config options as [described here](https://docs.npmjs.com/misc/config) where the configuration is `@sap:registry https://npm.sap.com` as [described here](https://blogs.sap.com/2017/11/09/install-the-node.js-driver-for-sap-hana-in-under-a-minute/)

**Comment by alex-slynko** [comment]
@michaelgrifalconi Unfortunately, this is a bug in Kubernetes. https://github.com/kubernetes/kubernetes/pull/69415

It worth mentioning your use-case in that bug, so it will get more attention. Unfortunately, it won't land in Kubernetes soon. 

We don't plan to implement a workaround for this in Eirini in the near future.

**Comment by michaelgrifalconi** [comment]
Thank you @alex-slynko for the clarification!
