### ISSUE TITLE
UAA Pod doesn't get ready with a valid certificate and domain configured

### ISSUE THREAD

**Issue by firasnajjar** [cloudfoundry-incubator/eirini-release#77]
### Description
I think there is an issue in this line: 
https://github.com/cloudfoundry-incubator/eirini-release/blob/master/helm/uaa/templates/uaa.yaml#L315

The problem is that I'm using certificate that is signed for the uaa domain. I'm using the default uaa.<my domain> for uaa. The problem is that the uaa pod never gets ready. This happens because the curl in the line above fails since my certificate doesn't have the domain: "uaa" signed in it. 

### Steps to reproduce

Deploy with a signed certificate for uaa.<your domain> or any uaa domain you choose.

### What was expected to happen

 UAA pods won't get ready

### What actually happened

The readiness probe fails.

### Suggested fix (optional)

The probe should check if there is a valid certificate and a domain configured, then it should use the configured domain in the check.

### Additional information (optional)

  [Fill in]

**Comment by julz** [comment]
Hi @firasnajjar - I think this issue might be better raised with the https://github.com/cloudfoundry-incubator/fissile team. /cc @ viovanov
