### ISSUE TITLE
Eirini docker image tag 'latest' missing

### ISSUE THREAD

**Issue by michaelgrifalconi** [cloudfoundry-incubator/eirini-release#82]
### Description

[The current version of the eirini helm chart](https://github.com/cloudfoundry-incubator/eirini-release/blob/30f0e59db15887f857bf5af9a2f8e73e13a8f0c1/helm/eirini/values.yaml#L11)  uses **latest** tag for its images.

Unfortunately **rootfs-patcher** images don't have a latest tag:
 - eirini/bits-waiter
   - [template](https://github.com/cloudfoundry-incubator/eirini-release/blob/30f0e59db15887f857bf5af9a2f8e73e13a8f0c1/helm/eirini/templates/rootfs-patcher.yml#L13)
   - [dockerhub image tags](https://hub.docker.com/r/eirini/bits-waiter/tags)
 - eirini/rootfs-patcher
   - [template](https://github.com/cloudfoundry-incubator/eirini-release/blob/30f0e59db15887f857bf5af9a2f8e73e13a8f0c1/helm/eirini/templates/rootfs-patcher.yml#L26)
   - [dockerhub image tags](https://hub.docker.com/r/eirini/rootfs-patcher/tags)
### Steps to reproduce

 Try to deploy the helm chart. Kubernetes will not be able to pull these images.

### Suggested fix

As workaround, we changed the [mentioned template](https://github.com/cloudfoundry-incubator/eirini-release/blob/30f0e59db15887f857bf5af9a2f8e73e13a8f0c1/helm/eirini/templates/rootfs-patcher.yml)
```
 image: eirini/bits-waiter:{{ .Values.opi.image_tag }}
 image: eirini/rootfs-patcher:{{ .Values.opi.image_tag }}
```

with
```
 image: eirini/bits-waiter:ci-57.0.0
 image: eirini/rootfs-patcher:ci-57.0.0
```
 
It was not possible to use **ci-57.0.0** as global value in [values.yaml](https://github.com/cloudfoundry-incubator/eirini-release/blob/30f0e59db15887f857bf5af9a2f8e73e13a8f0c1/helm/eirini/values.yaml#L11) because helm would then try to change the image of already finished jobs and fail with `Field is immutable error`.

**Comment by JulzDiverse** [comment]
Hi @michaelgrifalconi, 
sorry for the late response. 
In the meanwhile we are creating the `latest` tag also for the `bits-waiter` image.
