### ISSUE TITLE
Locket fails to start due to the container being non-privileged

### ISSUE THREAD

**Issue by giner** [cloudfoundry-incubator/eirini-release#86]
When deploying Eirini 0.13.0 on a fresh environment (microk8s) locket fails to start with the following error: `ulimit: open files: cannot modify limit: Operation not permitted`.

The following part of configuration seems to be related https://github.com/cloudfoundry-incubator/eirini-release/blob/v0.13.0/helm/cf/templates/locket.yaml#L376-L378.

**Comment by gdankov** [comment]
Hey @giner,

Do you still have this issue? If I recall correctly there was a recent slack message by you saying that you tried 1.0 and everything worked fine. If that's the case, can you please close this?

BR,
Georgi

**Comment by giner** [comment]
@gdankov it used to work before also but required a work around. I'll check come back.

**Comment by giner** [comment]
The issue seems to be solved with one of scf bumps. Closing.
