### ISSUE TITLE
Eirini-cf failing with error "diego_ssh must have at least 1 instances"

### ISSUE THREAD

**Issue by KesavanKing** [cloudfoundry-incubator/eirini-release#88]
### Description

  I am deploying eirini-release on GKE cluster. When I deploy eirini-cf I am getting the following error
`Error: render error in "cf/templates/diego-ssh.yaml": template: cf/templates/diego-ssh.yaml:181:17: executing "cf/templates/diego-ssh.yaml" at <fail "diego_ssh must have at least 1 instances">: error calling fail: diego_ssh must have at least 1 instances`

From the templates I can see default was set to 1 and min_replicas [181](https://github.com/cloudfoundry-incubator/eirini-release/blob/9e4b4f77f011663bfb470e3fee255aabc46d6192/helm/cf/templates/diego-ssh.yaml#L181)

### Steps to reproduce

 Deploy eirini-release latest release on GKE.

**Comment by mnitchev** [comment]
Hello,
We changed the way we disable Diego components when opi staging is enabled, so you shouldn't see this error anymore. The templates are already on master.
