### ISSUE TITLE
Converting values.yaml to a template

### ISSUE THREAD

**Issue by giner** [cloudfoundry-incubator/eirini-release#91]
Converting [values.yaml](https://github.com/cloudfoundry-incubator/eirini-release/blob/master/values.yaml) to a proper template would help in getting a development environment in an automated fashion without a need for unreliable replacements like this https://github.com/giner/eirini-on-microk8s/blob/3a788e3/Vagrantfile#L193-L201.

**Comment by schaefm-ibm** [comment]
@giner , see https://github.com/cloudfoundry-incubator/eirini-release/commit/9af5aa90aa7ea695641d253e23cd460ef69454b3 if that is what you would like to have

**Comment by giner** [comment]
@schaefm-ibm, nice, that will do.

**Comment by alex-slynko** [comment]
merged into develop
