### ISSUE TITLE
loggregator-fluentd doesn't read logs from docker containers

### ISSUE THREAD

**Issue by giner** [cloudfoundry-incubator/eirini-release#93]
`cf logs` shows only API logs if docker is used on k8s cluster.
Here is what I found to be the cause:
```
$ kubectl -n scf log loggregator-fluentd-ggwpj loggregator-fluentd --tail=100 | grep scf_router | tail -n1
2019-07-14 14:55:46 +0000 [warn]: #0 [in_tail_container_logs] /var/log/containers/router-0_scf_router-215f3442d0d4ad6cf77e79619899434cc0a6fc7250e34018ca3a294a9637b559.log unreadable. It is excluded and would be examined next time.

root@loggregator-fluentd-ggwpj:~# stat $(readlink -m /var/log/containers/router-0_scf_router-215f3442d0d4ad6cf77e79619899434cc0a6fc7250e34018ca3a294a9637b559.log)
stat: cannot stat '/var/lib/docker/containers/215f3442d0d4ad6cf77e79619899434cc0a6fc7250e34018ca3a294a9637b559/215f3442d0d4ad6cf77e79619899434cc0a6fc7250e34018ca3a294a9637b559-json.log': No such file or directory
```

The following change mostly (with an [exception](https://www.pivotaltracker.com/n/projects/2172361/stories/165745052) for RTR logs) made it work for me (found [here](https://github.com/SUSE/scf/blob/7c97351df3332bc1b0ec4438050b4db3ff5e8d95/src/scf-release/jobs/configure-scf/templates/eirini-daemonset.yaml.erb)):
```
$ git diff helm/eirini/templates/daemonset-fluentd.yaml
diff --git a/helm/eirini/templates/daemonset-fluentd.yaml b/helm/eirini/templates/daemonset-fluentd.yaml
index f63477a..e899789 100644
--- a/helm/eirini/templates/daemonset-fluentd.yaml
+++ b/helm/eirini/templates/daemonset-fluentd.yaml
@@ -43,6 +43,9 @@ spec:
           mountPath: /var/data
         - name: varlog
           mountPath: /var/log
+        - name: varlibdockercontainers
+          mountPath: /var/lib/docker/containers
+          readOnly: true
         - name: config-volume
           mountPath: /fluentd/etc/
           readOnly: false
@@ -80,6 +83,9 @@ spec:
       - name: varlog
         hostPath:
           path: /var/log
+      - name: varlibdockercontainers
+        hostPath:
+          path: /var/lib/docker/containers
       - name: fluentd-conf
         configMap:
           name: fluentd-conf
``` 

There is still one concern though. I've noticed that loggregator-fluentd is trying to read logs from all containers on a particular node no matter if the containers have been deployed with Eirini or not. Is this a bug or Eirini should be using dedicated nodes?

**Comment by julz** [comment]
Hi @giner - right now we're focusing on supporting containerd rather than dockerd, but we would happily accept a PR for docker support. We believe the logs are filtered to only containers in the`eirini` namespace [here](https://github.com/cloudfoundry-incubator/eirini-release/blob/master/helm/eirini/templates/fluentd-configmap.yaml#L41). 

Additionally you may be interested in [this extension project](https://github.com/suse/eirini-loggregator-bridge).

Thanks!

**Comment by giner** [comment]
Hi @julz, they are filtered for output fluentd still reads all of them https://github.com/cloudfoundry-incubator/eirini-release/blob/7a1cf08/helm/eirini/templates/fluentd-configmap.yaml#L15. Should they be excluded from source?
