### ISSUE TITLE
Cannot push due to missing registry credentials

### ISSUE THREAD

**Issue by giner** [cloudfoundry-incubator/eirini-release#94]
### Description

I'm unable to push an app to the Eirini deployed from the master branch.

### Steps to reproduce

Deploy the Eirini with helm from the master branch.

### What was expected to happen

cf push works

### What actually happened

An application image cannot be pulled from the registry due to authentication failure.
```
104s        Warning   Failed             pod/hello-myspace-bc646f02de-0                   Failed to pull image "registry.192.168.51.101.nip.io:6666/cloudfoundry/5094703d-48c1-4600-8f21-f1df72a6e049:32a07ba5175cd9ce32f48d3f9d32df9da8379e5f": rpc error: code = Unknown desc = failed to resolve image "registry.192.168.51.101.nip.io:6666/cloudfoundry/5094703d-48c1-4600-8f21-f1df72a6e049:32a07ba5175cd9ce32f48d3f9d32df9da8379e5f": no available registry endpoint: unexpected status code https://registry.192.168.51.101.nip.io:6666/v2/cloudfoundry/5094703d-48c1-4600-8f21-f1df72a6e049/manifests/32a07ba5175cd9ce32f48d3f9d32df9da8379e5f: 401 Unauthorized
```

### Suggested fix (optional)

It looks like the tag `latest` for `secret-smuggler` which is used in Eirini release does not include the following change: https://github.com/cloudfoundry-incubator/eirini/commit/4e8c8fe7fa2062e823fb1db6ec9b46aa9c6c3853 so it has to be updated.

### Additional information (optional)

Should the master branch have the fixed versions of images? Any other ways to ensure the master branch working?

**Comment by giner** [comment]
Specifying `--set "eirini.opi.image_tag=acceptance-55.0.0"` to `helm install ..` (suggested by @mnitchev) makes it work.

**Comment by alex-slynko** [comment]
Starting from now, helm uses sha256 for all Eirini images.
